[build]
  functions = "netlify/functions"
  publish = "src"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
